services:
    db:
        image: mysql:5.7
        container_name: laravel_mysql
        networks:
            - app-network
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: shop
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - ./data:/var/lib/mysql
networks:
    app-network:
        driver: bridge
